development:
  adapter: postgresql
  database: personal_page_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: personal_page_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: personal_page
  pool: 5
  timeout: 5000